---
# values-prod.yaml
replicaCount: 4

deploymentStrategy:
  type: canary
canary:
  steps:
    - setWeight: 10
    - pause: {duration: 10m}
    - setWeight: 30
    - pause: {duration: 10m}
    - setWeight: 50
    - pause: {duration: 10m}
    - setWeight: 70
    - pause: {duration: 10m}
    - setWeight: 100
  stableService:
    enabled: true
    type: NodePort
    port: 80
    nodePort: null
  canaryService:
    enabled: true
    type: NodePort
    port: 80
    nodePort: null

ingress:
  enabled: true
  name: vote
  host: vote.example.com

